# Generated by Django 4.2 on 2025-05-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="flag",),
    ]
