# Generated by Django 4.2 on 2025-05-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_remove_customuser_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="modified_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="modified_time",
            field=models.TimeField(auto_now=True),
        ),
    ]
