# Generated by Django 4.2 on 2025-06-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_backgroundtaskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtaskstatus',
            name='model_id',
            field=models.CharField(max_length=200),
        ),
    ]
