# Generated by Django 4.2 on 2025-04-27 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now_add=True)),
                ("modified_time", models.TimeField(auto_now_add=True)),
                ("flag", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField()),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now_add=True)),
                ("modified_time", models.TimeField(auto_now_add=True)),
                ("flag", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(default=0)),
                ("offer", models.FloatField(default=0)),
                ("thumbnail", models.ImageField(upload_to="courses")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="StudentId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now_add=True)),
                ("modified_time", models.TimeField(auto_now_add=True)),
                ("flag", models.BooleanField(default=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="teachers"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="SubChapters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now_add=True)),
                ("modified_time", models.TimeField(auto_now_add=True)),
                ("flag", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("video_url", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="courses/chapters")),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_chapter",
                        to="web.chapter",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now_add=True)),
                ("modified_time", models.TimeField(auto_now_add=True)),
                ("flag", models.BooleanField(default=True)),
                ("group_code", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="students"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now_add=True)),
                ("modified_time", models.TimeField(auto_now_add=True)),
                ("flag", models.BooleanField(default=True)),
                ("payment_id", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("in_progress", "In progress"),
                            ("failed", "Failed"),
                        ]
                    ),
                ),
                (
                    "course_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchased_course",
                        to="web.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchased_student",
                        to="web.student",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="course",
            name="tutor",
            field=models.ManyToManyField(related_name="courses", to="web.tutor"),
        ),
        migrations.AddField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_chapter",
                to="web.course",
            ),
        ),
        migrations.CreateModel(
            name="ChapterProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("watched_duration", models.IntegerField(default=0)),
                ("last_watched_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="web.chapter",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_progress",
                        to="web.student",
                    ),
                ),
            ],
            options={"unique_together": {("student", "chapter")},},
        ),
    ]
