# Generated by Django 4.2 on 2025-04-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="title",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
