# Generated by Django 4.2 on 2025-04-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_purchase_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("watched_duration", models.IntegerField(default=0)),
                ("last_watched_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="web.chapter",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_progress",
                        to="web.student",
                    ),
                ),
            ],
            options={"unique_together": {("student", "chapter")},},
        ),
    ]
