# Generated by Django 4.2 on 2025-04-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_student_student_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapterprogress",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_progress",
                to="web.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="chapterprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_progress",
                to="web.student",
            ),
        ),
    ]
