# Generated by Django 4.2 on 2025-04-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_chapterprogress"),
    ]

    operations = [
        migrations.RemoveField(model_name="chapter", name="thumbnail",),
        migrations.RemoveField(model_name="chapter", name="video_url",),
        migrations.AlterField(
            model_name="chapter",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="group_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="SubChapters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now_add=True)),
                ("modified_time", models.TimeField(auto_now_add=True)),
                ("flag", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("video_url", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="courses/chapters")),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_chapter",
                        to="web.chapter",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
