# Generated by Django 4.2 on 2025-04-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_chapterprogress_chapter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
    ]
