# Generated by Django 4.2 on 2025-05-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_chapter_is_free"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now_add=True)),
                ("modified_time", models.TimeField(auto_now_add=True)),
                ("flag", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={"abstract": False,},
        ),
        migrations.AlterField(
            model_name="course",
            name="tutor",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="courses", to="web.tutor"
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="package",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchased_package",
                to="web.package",
            ),
        ),
    ]
