# Generated by Django 4.2 on 2025-05-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_rename_flag_chapter_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now_add=True)),
                ("modified_time", models.TimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={"abstract": False,},
        ),
        migrations.RemoveField(model_name="tutor", name="user",),
        migrations.RemoveField(model_name="chapter", name="course",),
        migrations.AddField(
            model_name="package",
            name="features",
            field=models.ManyToManyField(
                related_name="package_features", to="web.chapter"
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="thumbnail",
            field=models.ImageField(upload_to="chapters"),
        ),
        migrations.AlterField(
            model_name="subchapters",
            name="thumbnail",
            field=models.ImageField(upload_to="chapters/subchapters"),
        ),
        migrations.AlterField(
            model_name="subchapters",
            name="video_url",
            field=models.FileField(upload_to=""),
        ),
        migrations.DeleteModel(name="Course",),
        migrations.DeleteModel(name="Tutor",),
    ]
