# Generated by Django 4.2 on 2025-05-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_features_remove_tutor_user_remove_chapter_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="modified_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="modified_time",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="features",
            name="modified_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="features",
            name="modified_time",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="modified_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="modified_time",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="modified_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="modified_time",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="modified_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="modified_time",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subchapters",
            name="modified_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subchapters",
            name="modified_time",
            field=models.TimeField(auto_now=True),
        ),
    ]
