# Generated by Django 4.2 on 2025-05-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_rename_chapterprogress_subchapterprogress"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subchapterprogress", unique_together=set(),
        ),
        migrations.AddField(
            model_name="subchapterprogress",
            name="sub_chapter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_progress",
                to="web.subchapters",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="subchapterprogress", unique_together={("student", "sub_chapter")},
        ),
        migrations.RemoveField(model_name="subchapterprogress", name="chapter",),
    ]
