# Generated by Django 4.2 on 2025-05-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_alter_subchapterprogress_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subchapterprogress",
            name="sub_chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_chapter_progress",
                to="web.subchapters",
            ),
        ),
    ]
