# Generated by Django 4.2 on 2025-05-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_alter_subchapterprogress_sub_chapter"),
    ]

    operations = [
        migrations.RemoveField(model_name="chapter", name="is_free",),
    ]
