# Generated by Django 4.2 on 2025-05-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_remove_chapter_is_free"),
    ]

    operations = [
        migrations.AddField(
            model_name="subchapters",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
