# Generated by Django 4.2 on 2025-05-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_subchapters_is_completed"),
    ]

    operations = [
        migrations.RemoveField(model_name="subchapters", name="video_url",),
        migrations.AddField(
            model_name="subchapters",
            name="video",
            field=models.FileField(default=1, upload_to="subchapters/videos"),
            preserve_default=False,
        ),
    ]
