# Generated by Django 4.2 on 2025-05-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_remove_subchapters_video_url_subchapters_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="subchapters",
            name="watched_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
