# Generated by Django 4.2 on 2025-05-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_subchapters_watched_duration"),
    ]

    operations = [
        migrations.RemoveField(model_name="subchapters", name="watched_duration",),
    ]
