# Generated by Django 4.2 on 2025-05-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_remove_subchapters_watched_duration"),
    ]

    operations = [
        migrations.RemoveField(model_name="subchapters", name="is_completed",),
    ]
