# Generated by Django 4.2 on 2025-05-09 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_alter_package_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="subchapterprogress",
            name="created_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subchapterprogress",
            name="created_time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subchapterprogress",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subchapterprogress",
            name="modified_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subchapterprogress",
            name="modified_time",
            field=models.TimeField(auto_now=True),
        ),
    ]
