# Generated by Django 4.2 on 2025-05-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_subchapterprogress_created_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="StudentId", new_name="Batch",),
        migrations.AddField(
            model_name="student",
            name="batch",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="web.batch"
            ),
            preserve_default=False,
        ),
    ]
