# Generated by Django 4.2 on 2025-05-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_rename_studentid_batch_student_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
