# Generated by Django 4.2 on 2025-05-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0022_batch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
