# Generated by Django 4.2 on 2025-05-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_student_end_date_student_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.package'),
        ),
    ]
